services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind 0.0.0.0:8000 mokkapi.wsgi:application 
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mokkapi_db
      POSTGRES_USER: mokkapi_db_user
      POSTGRES_PASSWORD: mokkapi_db_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data: