# Generated by Django 5.1.6 on 2025-04-22 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique, user-friendly name for this authentication profile (e.g., 'Admin Key', 'Partner Basic Auth').", max_length=100, unique=True)),
                ('auth_type', models.CharField(choices=[('API_KEY', 'API Key'), ('BASIC', 'HTTP Basic Auth')], help_text='The type of authentication this profile uses.', max_length=20)),
                ('api_key', models.CharField(blank=True, db_index=True, help_text='The secret API key (auto-generated if left blank for API Key type).', max_length=128, null=True, unique=True)),
                ('basic_auth_username', models.CharField(blank=True, help_text='Username for HTTP Basic Authentication.', max_length=150, null=True)),
                ('basic_auth_password_hash', models.CharField(blank=True, help_text='Hashed password for HTTP Basic Authentication.', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who owns and manages this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='auth_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(db_index=True, help_text='The unique URL path fragment.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this endpoint.')),
                ('authentication', models.ForeignKey(blank=True, help_text='Optional authentication applied to all methods for this path.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_endpoints', to='core.authenticationprofile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Endpoint',
                'verbose_name_plural': 'Mock Endpoints',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='ResponseHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], db_index=True, help_text='The HTTP method this handler responds to.', max_length=10)),
                ('response_status_code', models.PositiveIntegerField(default=200, help_text='The HTTP status code to return.')),
                ('response_headers', models.JSONField(blank=True, default=dict, help_text='JSON object of response headers (e.g., {"Content-Type": "application/json"}).')),
                ('response_body', models.TextField(blank=True, help_text='The raw response body (JSON, XML, plain text, etc.).')),
                ('description', models.CharField(blank=True, help_text='Optional description for this specific method handler.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(help_text='The endpoint this handler belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='core.mockendpoint')),
            ],
            options={
                'verbose_name': 'Response Handler',
                'verbose_name_plural': 'Response Handlers',
                'ordering': ['endpoint__path', 'http_method'],
                'unique_together': {('endpoint', 'http_method')},
            },
        ),
    ]
