# Generated by Django 5.1.6 on 2025-04-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MokkBaseJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(help_text="The URL path to map (e.g., 'some/unique/path'), Leading/trailing slashes are ignored..", max_length=255, unique=True)),
                ('data', models.JSONField(help_text='The JSON object to be returned when this URL is requested.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
