# Generated by Django 6.0.1 on 2026-01-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('AUTH_FAILURE', 'Authentication Failure'), ('PERMISSION_DENIED', 'Permission Denied')], db_index=True, help_text='The type of action performed.', max_length=20)),
                ('endpoint_id', models.IntegerField(blank=True, db_index=True, help_text='The ID of the endpoint involved (null for non-endpoint actions).', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred.')),
                ('old_value', models.JSONField(blank=True, help_text='JSON representation of the previous state (null for CREATE).', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='JSON representation of the new state (null for DELETE).', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action (null for anonymous).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='core_auditl_user_id_4f5b78_idx'), models.Index(fields=['endpoint_id', 'action'], name='core_auditl_endpoin_f9969d_idx')],
            },
        ),
    ]
