# Generated by Django 5.1.6 on 2025-04-22 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=128, verbose_name='Client ID')),
                ('admin_email', models.EmailField(blank=True, max_length=254, verbose_name='Support email')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseStatus',
            fields=[
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='license.license')),
                ('is_commercial', models.BooleanField(default=False)),
                ('maintenance_valid', models.BooleanField(default=False)),
                ('maintenance_end_date', models.DateField(blank=True, null=True)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
